eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/
    healthcheck:
           enabled: true
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
server:
  port: 8091
spring:
  application:
    name: Goku.WebService.Cloud.zuul
zuul:
  routes:
    api-sys:
      path: /sys/**
      serviceId: Goku.WebService.Cloud.sys.client
    api-blog:
      path: /blog/**
      serviceId: Goku.WebService.Cloud.blog.client

