eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/
server:
  port: 8091
spring:
  application:
    name: Goku.WebService.Cloud.zuul
zuul:
  routes:
    api-sys:
      path: /sys/**
      serviceId: Goku.WebService.Cloud.sys.webapi
    api-blog:
      path: /blog/**
      serviceId: Goku.WebService.Cloud.blog.webapi

