eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/
server:
  port: 8021
spring:
  application:
    name: Goku.WebService.Cloud.config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/nbfujx/Goku.WebService.Cloud.config/    # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                            # git仓库的账号
          password:
          strict-host-key-checking: false