eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/
server:
  port: 8081
spring:
  application:
    name: Goku.WebService.Cloud.sys.webapi
feign:
  hystrix:
    enabled: true

