eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/
    healthcheck:
       enabled: true
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
server:
  port: 8081
spring:
  application:
    name: Goku.WebService.Cloud.sys.client
feign:
  hystrix:
    enabled: true
hystrix:
  command:
      default:
        execution:
          timeout:
            enabled: false

